<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gamewright.Graphics\Gamewright.Graphics.csproj" />
    <ProjectReference Include="..\Gamewright.SquareBoard\Gamewright.SquareBoard.csproj" />
  </ItemGroup>

</Project>
