namespace Gamewright.CodeGen;

using System.Text;
using System.Text.Json;

public static class CSharpBindingEmitter
{
    public static string Emit(ShaderGenerationInput input)
    {
        ArgumentNullException.ThrowIfNull(input);
        ValidateUniformSignatures(input);
        var blockBindings = GetBlockBindings(input);

        var result = new StringBuilder();
        result.AppendLine("// <auto-generated />");
        result.Append("namespace ").Append(input.Namespace).AppendLine(";");
        result.AppendLine();

        foreach (var program in input.Programs.OrderBy(program => program.Name, StringComparer.Ordinal))
        {
            EmitProgram(result, program, blockBindings);
        }

        return result.ToString();
    }

    private static void EmitProgram(
        StringBuilder result,
        ShaderProgramInput program,
        IReadOnlyDictionary<string, int> blockBindings)
    {
        result.Append("internal static class ").Append(program.Name).AppendLine("ShaderBindings");
        result.AppendLine("{");
        EmitStringConstant(result, "VertexSource", program.Vertex.Source.RuntimeSource);
        EmitStringConstant(result, "FragmentSource", program.Fragment.Source.RuntimeSource);

        var declarations = program.Vertex.Declarations.Concat(program.Fragment.Declarations).ToArray();
        foreach (var attribute in program.Vertex.Declarations.OfType<VariableDeclaration>()
                     .Where(declaration => declaration.Kind == DeclarationKind.Input)
                     .OrderBy(GetRequiredLocation))
        {
            result.Append("    public const int Attribute")
                .Append(ToPascalIdentifier(attribute.Name))
                .Append("Location = ")
                .Append(GetRequiredLocation(attribute))
                .AppendLine(";");
        }

        foreach (var uniform in declarations.OfType<VariableDeclaration>()
                     .Where(declaration => declaration.Kind == DeclarationKind.Uniform)
                     .DistinctBy(declaration => declaration.Name)
                     .OrderBy(declaration => declaration.Name, StringComparer.Ordinal))
        {
            var propertyName = ToPascalIdentifier(uniform.Name);
            var location = GetOptionalIntegerQualifier(uniform.Layout, "location");
            if (location is { } explicitLocation)
            {
                result.Append("    public const int Uniform")
                    .Append(propertyName)
                    .Append("Location = ")
                    .Append(explicitLocation)
                    .AppendLine(";");
            }
            else
            {
                EmitStringConstant(result, $"Uniform{propertyName}Name", uniform.Name, indentation: 4);
            }
        }

        foreach (var block in declarations.OfType<InterfaceBlockDeclaration>()
                     .DistinctBy(declaration => declaration.BlockName)
                     .OrderBy(declaration => declaration.BlockName, StringComparer.Ordinal))
        {
            EmitStringConstant(
                result,
                $"{ToPascalIdentifier(block.BlockName)}BlockName",
                block.BlockName,
                indentation: 4);
            result.Append("    public const int ")
                .Append(ToPascalIdentifier(block.BlockName))
                .Append("Binding = ")
                .Append(blockBindings[block.BlockName])
                .AppendLine(";");
        }

        result.AppendLine("}");
        result.AppendLine();
    }

    private static void ValidateUniformSignatures(ShaderGenerationInput input)
    {
        var uniforms = input.Programs
            .SelectMany(program => program.Vertex.Declarations.Concat(program.Fragment.Declarations))
            .OfType<VariableDeclaration>()
            .Where(declaration => declaration.Kind == DeclarationKind.Uniform)
            .GroupBy(declaration => declaration.Name, StringComparer.Ordinal);

        foreach (var group in uniforms)
        {
            var signatures = group
                .Select(declaration => (declaration.Type, declaration.Array))
                .Distinct()
                .ToArray();
            if (signatures.Length > 1)
            {
                throw new InvalidOperationException($"Uniform '{group.Key}' has conflicting types across shaders.");
            }
        }
    }

    private static IReadOnlyDictionary<string, int> GetBlockBindings(ShaderGenerationInput input)
    {
        var blocks = input.Programs
            .SelectMany(program => program.Vertex.Declarations.Concat(program.Fragment.Declarations))
            .OfType<InterfaceBlockDeclaration>()
            .GroupBy(block => block.BlockName, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal)
            .ToArray();
        var result = new Dictionary<string, int>(StringComparer.Ordinal);
        var usedBindings = new HashSet<int>();

        foreach (var group in blocks)
        {
            var explicitBindings = group
                .Select(block => GetOptionalIntegerQualifier(block.Layout, "binding"))
                .Where(binding => binding.HasValue)
                .Select(binding => binding!.Value)
                .Distinct()
                .ToArray();
            if (explicitBindings.Length > 1)
            {
                throw new InvalidOperationException($"Interface block '{group.Key}' has conflicting bindings.");
            }

            if (explicitBindings.Length == 1)
            {
                if (!usedBindings.Add(explicitBindings[0]))
                {
                    throw new InvalidOperationException($"Buffer binding {explicitBindings[0]} is assigned to multiple interface blocks.");
                }

                result.Add(group.Key, explicitBindings[0]);
            }
        }

        var nextBinding = 0;
        foreach (var group in blocks.Where(group => !result.ContainsKey(group.Key)))
        {
            while (usedBindings.Contains(nextBinding))
            {
                nextBinding++;
            }

            result.Add(group.Key, nextBinding);
            usedBindings.Add(nextBinding++);
        }

        return result;
    }

    private static int GetRequiredLocation(VariableDeclaration declaration)
    {
        return GetRequiredIntegerQualifier(declaration.Layout, "location", declaration.Location);
    }

    private static int GetRequiredIntegerQualifier(
        IReadOnlyList<LayoutQualifier> layout,
        string name,
        SourceLocation location)
    {
        return GetOptionalIntegerQualifier(layout, name)
            ?? throw new GlslSyntaxException($"Expected layout qualifier '{name}'", location);
    }

    private static int? GetOptionalIntegerQualifier(IReadOnlyList<LayoutQualifier> layout, string name)
    {
        var qualifier = layout.SingleOrDefault(item => item.Name == name);
        if (qualifier == default)
        {
            return null;
        }

        return int.TryParse(qualifier.Value, out var value)
            ? value
            : throw new GlslSyntaxException(
                $"Layout qualifier '{name}' must be an integer",
                new SourceLocation(0, 1, 1));
    }

    private static void EmitStringConstant(StringBuilder result, string name, string value, int indentation = 4)
    {
        result.Append(' ', indentation)
            .Append("public const string ")
            .Append(name)
            .Append(" = ")
            .Append(JsonSerializer.Serialize(value))
            .AppendLine(";");
    }

    private static string ToPascalIdentifier(string value)
    {
        var result = new StringBuilder(value.Length);
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }

            result.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        return result.Length > 0 ? result.ToString() : "Value";
    }
}
